-- ============================================================================
-- NYX DRIPSTORE - INITIAL SEED PRODUCTS & INVENTORY
-- Execute after running schema.sql to populate initial hardware catalog
-- ============================================================================

INSERT INTO public.products (
  id, name, slug, description, price, original_price, category_name, style, colors, materials, rating, review_count, stock, badge, images, tags, is_new_arrival, is_best_seller
) VALUES
(
  'a0000001-0000-0000-0000-000000000001',
  'Chrome Cross Pendant',
  'chrome-cross-pendant',
  'Monolithic sculpted gothic cross forged in solid 316L surgical stainless steel. Finished with our proprietary vacuum PVD mirror-chrome immersion process. Built for midnight rituals and eternal wear.',
  1299.00,
  1699.00,
  'Pendants',
  'Gothic',
  ARRAY['Chrome', 'Silver']::TEXT[],
  'Solid 316L Surgical Steel, Mirror PVD Chrome',
  4.95,
  142,
  24,
  'BESTSELLER',
  ARRAY['/assets/hero-cross.jpg']::TEXT[],
  ARRAY['cross', 'pendant', 'gothic', 'chrome', 'y2k', 'steel']::TEXT[],
  false,
  true
),
(
  'a0000001-0000-0000-0000-000000000002',
  'Gothic Heart Pendant',
  'gothic-heart-pendant',
  'Anatomically inspired cyber heart pendant with spiked filigree branches and barbed wire wrapping. Hypoallergenic, tarnish-proof, and designed to sit heavy over dark streetwear silhouettes.',
  1099.00,
  1499.00,
  'Pendants',
  'Y2K',
  ARRAY['Silver', 'Obsidian']::TEXT[],
  'Solid 316L Surgical Steel',
  4.88,
  98,
  16,
  'NEW',
  ARRAY['/assets/heart-pendant.jpg']::TEXT[],
  ARRAY['heart', 'pendant', 'y2k', 'spikes', 'gothic', 'dark']::TEXT[],
  true,
  false
),
(
  'a0000001-0000-0000-0000-000000000003',
  'Black Fang Necklace',
  'black-fang-necklace',
  'High-density obsidian titanium carbide tooth cast on an interlocking curb chain. Corrosion-proof, sweat-proof, and impervious to ocean water or humidity.',
  899.00,
  1199.00,
  'Pendants',
  'Industrial',
  ARRAY['Obsidian', 'Gunmetal']::TEXT[],
  'Obsidian Titanium-Nitride Alloy',
  4.92,
  76,
  19,
  NULL,
  ARRAY['/assets/fang-necklace.jpg']::TEXT[],
  ARRAY['fang', 'necklace', 'black', 'titanium', 'cyber']::TEXT[],
  false,
  false
),
(
  'a0000001-0000-0000-0000-000000000004',
  'Y2K Cyber Bracelet',
  'y2k-cyber-bracelet',
  'Segmented robotic armor plates interlinked with heavy industrial tension pins. Inspired by early 2000s Japanese cyberpunk mech design and brutalist underground hardware.',
  1499.00,
  1999.00,
  'Bracelets',
  'Cyber',
  ARRAY['Chrome', 'Silver']::TEXT[],
  'Vacuum-Coated Surgical Steel & Alloy Mesh',
  4.97,
  215,
  12,
  'LIMITED',
  ARRAY['/assets/cyber-bracelet.jpg']::TEXT[],
  ARRAY['bracelet', 'cyber', 'mech', 'y2k', 'heavy', 'armor']::TEXT[],
  true,
  true
),
(
  'a0000001-0000-0000-0000-000000000005',
  'Shadow Chain Bracelet',
  'shadow-chain-bracelet',
  'Double-stacked curb links treated with an acid-washed gunmetal patina. Smooth internal face prevents pinching or hair snagging. Features our custom spring-lock vault clasp.',
  999.00,
  1399.00,
  'Bracelets',
  'Gothic',
  ARRAY['Gunmetal', 'Obsidian']::TEXT[],
  'Acid-Washed 316L Steel',
  4.85,
  112,
  28,
  NULL,
  ARRAY['/assets/shadow-bracelet.jpg']::TEXT[],
  ARRAY['chain', 'bracelet', 'shadow', 'gunmetal', 'curb']::TEXT[],
  false,
  false
),
(
  'a0000001-0000-0000-0000-000000000006',
  'Midnight Heavy Cuban Chain',
  'midnight-heavy-cuban-chain',
  'Substantial 12mm beveled Cuban link necklace weighing 145 grams. Diamond-cut edges catch ambient nightclub lighting with cold metallic brilliance. Guaranteed lifetime against tarnish.',
  1899.00,
  2499.00,
  'Chains',
  'Industrial',
  ARRAY['Silver', 'Chrome']::TEXT[],
  'Solid 316L Surgical Grade Stainless Steel',
  4.99,
  310,
  8,
  'BESTSELLER',
  ARRAY['/assets/cuban-chain.jpg']::TEXT[],
  ARRAY['cuban', 'chain', 'heavy', '12mm', 'silver', 'choker']::TEXT[],
  false,
  true
),
(
  'a0000001-0000-0000-0000-000000000007',
  'Silver Spike Knuckle Ring',
  'silver-spike-knuckle-ring',
  'Triple-crested gothic pyramid spikes machined from solid sterling-coated alloy core. High-comfort comfort-fit interior band for continuous 24-hour daily wear.',
  699.00,
  999.00,
  'Rings',
  'Gothic',
  ARRAY['Silver']::TEXT[],
  'Surgical Steel with 925 Sterling Electro-Plating',
  4.82,
  64,
  30,
  NULL,
  ARRAY['/assets/spike-ring.jpg']::TEXT[],
  ARRAY['ring', 'spike', 'knuckle', 'silver', 'gothic']::TEXT[],
  false,
  false
),
(
  'a0000001-0000-0000-0000-000000000008',
  'Cyber Barbed Ring',
  'cyber-barbed-ring',
  'Interwoven barbed razor wire motif rendered in mirror-polished steel. Hypoallergenic design with rounded barbs for comfortable ergonomics and non-catch wearability.',
  599.00,
  799.00,
  'Rings',
  'Cyber',
  ARRAY['Chrome', 'Gunmetal']::TEXT[],
  'Solid 316L Surgical Steel',
  4.79,
  88,
  22,
  'NEW',
  ARRAY['/assets/barbed-ring.jpg']::TEXT[],
  ARRAY['ring', 'barbed', 'wire', 'razor', 'cyber', 'y2k']::TEXT[],
  true,
  false
),
(
  'a0000001-0000-0000-0000-000000000009',
  'Chrome Reinforced Dark Wallet',
  'chrome-reinforced-dark-wallet',
  'Matte black ballistic micro-grain leather reinforced with bolted chrome alloy corner guards and detachable steel wallet chain attachment loop. RFID-shielded internal lining.',
  1299.00,
  1799.00,
  'Wallets',
  'Industrial',
  ARRAY['Obsidian', 'Chrome']::TEXT[],
  'Grain Vegan Leather, 316L Chrome Corner Guards, RFID Shield',
  4.91,
  140,
  15,
  'BESTSELLER',
  ARRAY['/assets/chrome-wallet.jpg']::TEXT[],
  ARRAY['wallet', 'leather', 'chrome', 'rfid', 'chain', 'streetwear']::TEXT[],
  false,
  true
),
(
  'a0000001-0000-0000-0000-000000000010',
  'Angel Wings Relic Pendant',
  'angel-wings-relic-pendant',
  'Distressed blackened silver fallen angel wings embracing an embedded synthetic obsidian orb. High-relief 3D sculpted detailing on both front and back faces.',
  1199.00,
  1599.00,
  'Pendants',
  'Gothic',
  ARRAY['Silver', 'Obsidian']::TEXT[],
  'Antiqued 316L Surgical Steel & Obsidian Composite',
  4.93,
  105,
  18,
  'LIMITED',
  ARRAY['/assets/angel-pendant.jpg']::TEXT[],
  ARRAY['wings', 'angel', 'pendant', 'gothic', 'relic', 'black']::TEXT[],
  false,
  false
)
ON CONFLICT (slug) DO NOTHING;

-- Populate inventory rows for seeded products
INSERT INTO public.inventory (product_id, quantity, low_stock_threshold)
SELECT id, stock, 5 FROM public.products
ON CONFLICT (product_id) DO NOTHING;
